-- How many patients are registered in the hospital system?
SELECT
    COUNT(*) AS "Total Patients"
FROM warehouse.dim_patient;


-- Gender Distribution
SELECT
    "Gender",
    COUNT(*) AS "Total Patients"
FROM warehouse.dim_patient
GROUP BY "Gender"
ORDER BY "Total Patients" DESC;


-- Average Patient Age
SELECT
    ROUND(AVG("Age"),2) AS "Average Age"
FROM warehouse.dim_patient;


-- Youngest and Oldest Patient
SELECT
    MIN("Age") AS "Youngest Age",
    MAX("Age") AS "Oldest Age"
FROM warehouse.dim_patient;


-- Age Group Distribution
SELECT
CASE
    WHEN "Age" < 18 THEN 'Children'
    WHEN "Age" BETWEEN 18 AND 35 THEN 'Young Adults'
    WHEN "Age" BETWEEN 36 AND 55 THEN 'Adults'
    WHEN "Age" BETWEEN 56 AND 75 THEN 'Senior Adults'
    ELSE 'Elderly'
END AS "Age Group",
	COUNT(*) AS "Patients"
FROM warehouse.dim_patient
GROUP BY "Age Group"
ORDER BY "Patients" DESC;


-- Blood Type Distribution
SELECT
    "BloodType",
    COUNT(*) AS "Patients"
FROM warehouse.dim_patient
GROUP BY "BloodType"
ORDER BY "Patients" DESC;


-- Marital Status Distribution
SELECT
    "MaritalStatus",
    COUNT(*) AS "Patients"
FROM warehouse.dim_patient
GROUP BY "MaritalStatus"
ORDER BY "Patients" DESC;


-- Ethnicity Distribution
SELECT
    "Ethnicity",
    COUNT(*) AS "Patients"
FROM warehouse.dim_patient
GROUP BY "Ethnicity"
ORDER BY "Patients" DESC;


-- Patients by State
SELECT
    "State",
    COUNT(*) AS "Patients"
FROM warehouse.dim_patient
GROUP BY "State"
ORDER BY "Patients" DESC;


-- Top 10 Cities by Patient Count
SELECT
    "City",
    COUNT(*) AS "Patients"
FROM warehouse.dim_patient
GROUP BY "City"
ORDER BY "Patients" DESC
LIMIT 10;


-- Average Patient Satisfaction
SELECT
    ROUND(AVG("SatisfactionScore"),2) AS "Average Satisfaction",
    MIN("SatisfactionScore") AS "Minimum Score",
    MAX("SatisfactionScore") AS "Maximum Score"
FROM warehouse.fact_patient_visit;


-- Patient Registration Trend by Year
SELECT
    "RegistrationYear",
    COUNT(*) AS "Total Patients"
FROM warehouse.dim_patient
GROUP BY "RegistrationYear"
ORDER BY "RegistrationYear";


-- Readmission Analysis
SELECT
    "ReadmissionFlag",
    COUNT(*) AS "Total Visits",
    ROUND(
        COUNT(*) * 100.0 /
        SUM(COUNT(*)) OVER(),
        2
    ) AS "Percentage"
FROM warehouse.fact_patient_visit
GROUP BY "ReadmissionFlag"
ORDER BY "Total Visits" DESC;


-- Average Length of Stay by Gender
SELECT
    p."Gender",
    ROUND(
        AVG(f."LengthOfStayDays"),
        2
    ) AS "Average Stay"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_patient p
ON f."PatientKey" = p."PatientKey"
GROUP BY p."Gender"
ORDER BY "Average Stay" DESC;


-- Revenue Generated by Gender
SELECT
    p."Gender",
    SUM(f."TotalChargeUSD") AS "Total Revenue",

    ROUND(
        AVG(f."TotalChargeUSD"),
        2
    ) AS "Average Bill"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_patient p
ON f."PatientKey" = p."PatientKey"
GROUP BY p."Gender"
ORDER BY "Total Revenue" DESC;


-- Patient KPI Dashboard
SELECT
    COUNT(DISTINCT p."PatientKey") AS "Total Patients",

    ROUND(
        AVG(p."Age"),
        2
    ) AS "Average Age",

    ROUND(
        AVG(f."SatisfactionScore"),
        2
    ) AS "Average Satisfaction",

    ROUND(
        AVG(f."LengthOfStayDays"),
        2
    ) AS "Average Stay",

    SUM(f."TotalChargeUSD") AS "Total Revenue",

    COUNT(*) FILTER (
        WHERE f."ReadmissionFlag" = 1
    ) AS "Readmitted Patients"
FROM warehouse.dim_patient p
JOIN warehouse.fact_patient_visit f
ON p."PatientKey" = f."PatientKey";