-- What is the total revenue generated by the healthcare system?
SELECT
    SUM("TotalChargeUSD") AS "Total Revenue"
FROM warehouse.fact_patient_visit;


-- What is the average revenue generated per patient visit?
SELECT
    ROUND(AVG("TotalChargeUSD"),2) AS "Average Revenue Per Visit"
FROM warehouse.fact_patient_visit;


-- What is the highest bill amount charged?
SELECT
    MAX("TotalChargeUSD") AS "Highest Bill"
FROM warehouse.fact_patient_visit;


-- What is the lowest bill amount charged?
SELECT
    MIN("TotalChargeUSD") AS "Lowest Bill"
FROM warehouse.fact_patient_visit;


-- What is the monthly revenue trend?
SELECT
    d."Year",
    d."MonthName",
    SUM(f."TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_date d
ON f."DateKey"=d."DateKey"
GROUP BY
    d."Year",
    d."Month",
    d."MonthName"
ORDER BY
    d."Year",
    d."Month";


-- What is the yearly revenue trend?
SELECT
    d."Year",
    SUM(f."TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_date d
ON f."DateKey"=d."DateKey"
GROUP BY d."Year"
ORDER BY d."Year";


-- Which hospitals generated the highest revenue?
SELECT
    h."HospitalName",
    SUM(f."TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_hospital h
ON f."HospitalKey"=h."HospitalKey"
GROUP BY h."HospitalName"
ORDER BY "Revenue" DESC;


-- Which departments generated the highest revenue?
SELECT
    d."DepartmentName",
    SUM(f."TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_department d
ON f."DepartmentKey"=d."DepartmentKey"
GROUP BY d."DepartmentName"
ORDER BY "Revenue" DESC;


-- Which doctors generated the highest revenue?
SELECT
    doc."FullName",
    SUM(f."TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_doctor doc
ON f."DoctorKey"=doc."DoctorKey"
GROUP BY doc."FullName"
ORDER BY "Revenue" DESC
LIMIT 10;


-- Which treatments generated the highest revenue?
SELECT
    t."TreatmentName",
    SUM(f."TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_treatment t
ON f."TreatmentKey"=t."TreatmentKey"
GROUP BY t."TreatmentName"
ORDER BY "Revenue" DESC;


-- What is the total treatment cost?
SELECT
    SUM("TreatmentCostUSD") AS "Total Treatment Cost"
FROM warehouse.fact_patient_visit;


-- What is the total medicine cost?
SELECT
    SUM("MedicineCostUSD") AS "Total Medicine Cost"
FROM warehouse.fact_patient_visit;


-- What is the total room charge?
SELECT
    SUM("RoomChargeUSD") AS "Total Room Charge"
FROM warehouse.fact_patient_visit;


-- What is the total laboratory charge?
SELECT
    SUM("LabChargeUSD") AS "Total Laboratory Charge"
FROM warehouse.fact_patient_visit;


-- What is the total miscellaneous charge?
SELECT
    SUM("MiscChargeUSD") AS "Total Miscellaneous Charge"
FROM warehouse.fact_patient_visit;


-- What is the average treatment cost per visit?
SELECT
    ROUND(AVG("TreatmentCostUSD"),2) AS "Average Treatment Cost"
FROM warehouse.fact_patient_visit;


-- What is the average medicine cost per visit?
SELECT
    ROUND(AVG("MedicineCostUSD"),2) AS "Average Medicine Cost"
FROM warehouse.fact_patient_visit;


-- What is the total insurance coverage amount?
SELECT
    SUM("InsuranceCoverageUSD") AS "Total Insurance Coverage"
FROM warehouse.fact_patient_visit;


-- What is the total amount paid by patients?
SELECT
    SUM("PatientPaidUSD") AS "Total Patient Payment"
FROM warehouse.fact_patient_visit;


-- What is the total outstanding amount?
SELECT
    SUM("OutstandingAmtUSD") AS "Total Outstanding Amount"
FROM warehouse.fact_patient_visit;


-- What is the total discount provided?
SELECT
    SUM("DiscountAmtUSD") AS "Total Discount"
FROM warehouse.fact_patient_visit;


-- What percentage of the total revenue was covered by insurance?
SELECT
    ROUND(
        (SUM("InsuranceCoverageUSD") * 100.0) /
        SUM("TotalChargeUSD"),
        2
    ) AS "Insurance Coverage %"
FROM warehouse.fact_patient_visit;


-- Which insurance providers covered the highest amount?
SELECT
    i."ProviderName",
    SUM(f."InsuranceCoverageUSD") AS "Coverage Amount"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_insurance i
ON f."InsuranceKey" = i."InsuranceKey"
GROUP BY i."ProviderName"
ORDER BY "Coverage Amount" DESC;


-- Which hospitals generated the highest revenue?
SELECT
    h."HospitalName",
    SUM(f."TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_hospital h
ON f."HospitalKey" = h."HospitalKey"
GROUP BY h."HospitalName"
ORDER BY "Revenue" DESC
LIMIT 10;


-- Which doctors generated the highest revenue?
SELECT
    d."FullName",
    SUM(f."TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit f
JOIN warehouse.dim_doctor d
ON f."DoctorKey" = d."DoctorKey"
GROUP BY d."FullName"
ORDER BY "Revenue" DESC
LIMIT 10;


-- How much revenue was generated for each severity level?
SELECT
    "SeverityLevel",
    SUM("TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit
GROUP BY "SeverityLevel"
ORDER BY "Revenue" DESC;


-- How much revenue was generated for each visit type?
SELECT
    "VisitType",
    SUM("TotalChargeUSD") AS "Revenue"
FROM warehouse.fact_patient_visit
GROUP BY "VisitType"
ORDER BY "Revenue" DESC;


-- Executive Financial KPI Dashboard
SELECT
    SUM("TotalChargeUSD") AS "Total Revenue",
    ROUND(AVG("TotalChargeUSD"),2) AS "Average Bill",
    SUM("TreatmentCostUSD") AS "Treatment Cost",
    SUM("MedicineCostUSD") AS "Medicine Cost",
    SUM("RoomChargeUSD") AS "Room Charges",
    SUM("LabChargeUSD") AS "Lab Charges",
    SUM("MiscChargeUSD") AS "Misc Charges",
    SUM("InsuranceCoverageUSD") AS "Insurance Coverage",
    SUM("PatientPaidUSD") AS "Patient Payments",
    SUM("OutstandingAmtUSD") AS "Outstanding Amount",
    SUM("DiscountAmtUSD") AS "Total Discount"
FROM warehouse.fact_patient_visit;